services:
  tests:
    command: ["bats", "--show-output-of-passing-tests", "--verbose-run", "tests/"]
    image: buildkite/plugin-tester:v4.1.1
    volumes:
      - ".:/plugin:ro"

  lint:
    image: buildkite/plugin-linter:v2.1.0
    command: ['--id', 'avaly/gcp-secret-manager']
    volumes:
      - ".:/plugin:ro"

  shellcheck:
    image: koalaman/shellcheck-alpine:v0.10.0
    command: ['shellcheck', '/plugin/hooks/environment']
    volumes:
      - ".:/plugin:ro"
