name: GCP Secret Manager
description: Read secrets from Google Cloud Secret Manager
author: https://github.com/avaly/gcp-secret-manager-buildkite-plugin
requirements:
  - gcloud
configuration:
  properties:
    credentials_file:
      type: string
    env:
      type: object
  additionalProperties: false
