steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files: hooks/**

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v3.1.0:
        id: avaly/gcp-secret-manager

  - label: ":docker: Tests"
    plugins:
      docker-compose#v5.10.0:
        run: tests
