#!/bin/bash

set -euo pipefail

echo "--- :googlecloud::key: Reading secrets from GCP Secret Manager"

initialized=""

function initialize() {
  if [[ "${initialized}" -eq "1" ]]; then
    return
  fi

  local result;
  local path;

  # shellcheck disable=SC2034
  path=$(which gcloud)
  result=$?
  if [[ $result -ne 0 ]]; then
    echo "gcloud binary is not available in \$PATH"
    exit 1
  fi

  if [ -v BUILDKITE_PLUGIN_GCP_SECRET_MANAGER_CREDENTIALS_FILE ]; then
    gcloud auth activate-service-account --key-file "${BUILDKITE_PLUGIN_GCP_SECRET_MANAGER_CREDENTIALS_FILE}"
  fi

  initialized="1"
}

function load_secret_into_env() {
  local export_name="$1"
  local secret_name="$2"
  local secret_value

  secret_value="$(get_secret_value "${secret_name}")"

  echo "Exporting secret ${secret_name} from GCP Secret Manager into environment variable ${export_name}"

  export "${export_name}=${secret_value}"
}

function get_secret_value() {
  local secret_name="$1"
  local secret_value
  # Create a temporary directory with both BSD and GNU mktemp
  TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'buildkiteXXXX')
  local SECRETS_TMP_FILE="$TMPDIR"/secrets.tmp

  gcloud secrets versions access latest --secret="${secret_name}" --out-file="${SECRETS_TMP_FILE}"
  secret_value=$(<"${SECRETS_TMP_FILE}")
  result=$?
  if [[ $result -ne 0 ]]; then
    rm "${SECRETS_TMP_FILE}"
    exit 1
  fi
  rm "${SECRETS_TMP_FILE}"

  echo "${secret_value}"
}

function strip_quotes() {
  echo "${1}" | sed "s/^[[:blank:]]*//g;s/[[:blank:]]*$//g;s/[\"']//g"
}

echo "Fetching secrets..."

# Parse env items
while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_GCP_SECRET_MANAGER_ENV_) ]] ; then
    initialize

    export_name="${name//BUILDKITE_PLUGIN_GCP_SECRET_MANAGER_ENV_/}"
    secret_name="$(strip_quotes "${!name}")"

    load_secret_into_env "${export_name}" "${secret_name}"
  fi
done < <(env | sort)
